# Generated by Django 3.0.7 on 2020-06-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='firstname',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='lastname',
            new_name='title',
        ),
    ]
